apiVersion: v1
# TODO PV NFS instead
kind: PersistentVolumeClaim
metadata:
  name: dwc-dp-analyser-workdir
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: {{ .Values.storage.class }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
