# Abstraction such the chart is supporting using secrets
# but allows injection from values or by cli through:
# --set rabbit.username=realusername
# --set rabbit.password=readlPasswore
{{- if .Values.rabbit.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rabbit.credentialsSecret }}
type: opaque
stringData:
  {{- $existing := lookup "v1" "Secret" .Release.Namespace "rabbitmq-credentials" }}
  {{- if $existing }}
  username: {{ index $existing.data "username" | b64dec | quote }}
  password: {{ index $existing.data "password" | b64dec | quote }}
  {{- else }}
  username: {{ .Values.rabbit.username | quote }}
  password: {{ .Values.rabbit.password | quote }}
  {{- end }}
{{ end}}
